'use client'

import { FiArrowLeft, FiCheck } from 'react-icons/fi'
import { useSettingsStore } from '../_store/settingsStore'
import { getQuotationById } from './MyQuotations'

const progressSteps = [
    { label: 'Submitted', state: 'done' },
    { label: 'Under Review', state: 'done' },
    { label: 'Quotation Ready', state: 'done' },
    { label: 'Contract', state: 'active' },
    { label: 'Completed', state: 'upcoming' },
]

const stepLabelStyles = {
    done: 'text-[#6F946F]',
    active: 'font-medium text-[#C26D3C]',
    upcoming: 'text-[#B8A89E]',
}

const StepIcon = ({ state }) => {
    if (state === 'done') {
        return (
            <div className="flex h-8 w-8 items-center justify-center rounded-full border border-[#7E9B71] bg-[#7E9B71] text-white">
                <FiCheck size={16} />
            </div>
        )
    }

    if (state === 'active') {
        return (
            <div className="flex h-8 w-8 items-center justify-center rounded-full border border-[#D39A70] bg-white">
                <div className="h-4 w-4 rounded-full border-2 border-[#B66636] bg-[#D7925F]" />
            </div>
        )
    }

    return <div className="h-8 w-8 rounded-full border border-[#E1D4CB] bg-white" />
}

const ContractAcceptedDetail = () => {
    const { selectedQuotationId, setCurrentView, setSelectedQuotationId } = useSettingsStore()
    const quotation = getQuotationById(selectedQuotationId)

    const handleBack = () => {
        setCurrentView('my-quotations')
        setSelectedQuotationId(null)
    }

    const handleHistory = () => {
        setCurrentView('my-quotations')
    }

    return (
        <div className="mx-auto w-full max-w-7xl rounded-2xl bg-[#F5F0EE30] p-5 shadow-md md:p-8">
            <div className="mb-5 flex items-center gap-3">
                <button
                    type="button"
                    onClick={handleBack}
                    className="flex h-9 w-9 items-center justify-center rounded-full border border-[#E5D5CD] bg-white text-[#8B6A55]"
                >
                    <FiArrowLeft size={16} />
                </button>
                <h2 className="text-xl font-semibold text-[#2C1810]">My Quotations</h2>
            </div>

            <div className="rounded-2xl border border-[#F0E4DE] bg-white px-4 py-8 shadow-sm md:px-8 md:py-10">
                <div className="mx-auto max-w-4xl text-center">
                    <div className="mx-auto flex h-16 w-16 items-center justify-center rounded-full border border-[#A9D8B1] bg-[#ECFAEF]">
                        <div className="flex h-8 w-8 items-center justify-center rounded-full border-2 border-[#5FA96B] text-[#2F8C47]">
                            <FiCheck size={16} />
                        </div>
                    </div>

                    <h3 className="mt-6 text-2xl font-semibold text-[#2C1810]">
                        {quotation?.id || 'Q-2026-0847'} has been accepted
                    </h3>
                    <p className="mx-auto mt-3 max-w-xl text-sm leading-6 text-[#8D7769]">
                        Thank you. Your contract is now being generated by our documentation team and
                        will appear in your Contract Inbox shortly.
                    </p>

                    <div className="mt-8 grid grid-cols-1 gap-5 border-y border-[#F3E8E2] py-5 text-center md:grid-cols-3">
                        <div>
                            <p className="text-[10px] font-semibold uppercase tracking-[0.16em] text-[#C8A18C]">
                                Accepted On
                            </p>
                            <p className="mt-2 text-sm font-medium text-[#B66636]">Jul 13, 2026 · 16:05</p>
                        </div>
                        <div>
                            <p className="text-[10px] font-semibold uppercase tracking-[0.16em] text-[#C8A18C]">
                                Current Status
                            </p>
                            <p className="mt-2 text-sm font-medium text-[#B66636]">
                                Contract Generation In Progress
                            </p>
                        </div>
                        <div>
                            <p className="text-[10px] font-semibold uppercase tracking-[0.16em] text-[#C8A18C]">
                                Total Amount
                            </p>
                            <p className="mt-2 text-sm font-medium text-[#B66636]">
                                {quotation?.total || '¥1,357,400'}
                            </p>
                        </div>
                    </div>

                    <div className="mt-8 hidden md:block">
                        <div className="relative mx-auto max-w-[840px] px-3">
                            <div className="absolute left-[8.5%] right-[8.5%] top-4 h-[2px] bg-[#E8DED8]" />
                            <div className="absolute left-[8.5%] right-[18%] top-4 h-[2px] bg-[#6F946F]" />

                            <div className="relative grid grid-cols-5">
                                {progressSteps.map((step) => (
                                    <div key={step.label} className="flex flex-col items-center">
                                        <StepIcon state={step.state} />
                                        <p className={`mt-3 text-sm ${stepLabelStyles[step.state]}`}>
                                            {step.label}
                                        </p>
                                    </div>
                                ))}
                            </div>
                        </div>
                    </div>

                    <div className="mt-8 space-y-3 md:hidden">
                        {progressSteps.map((step) => (
                            <div
                                key={step.label}
                                className="flex items-center gap-3 rounded-xl border border-[#F1E4DD] px-4 py-3"
                            >
                                <StepIcon state={step.state} />
                                <p className={`text-sm ${stepLabelStyles[step.state]}`}>{step.label}</p>
                            </div>
                        ))}
                    </div>

                    <div className="mt-8 flex flex-wrap justify-center gap-3">
                        <button
                            type="button"
                            className="rounded-md bg-[#A95A2C] px-5 py-2.5 text-sm font-semibold text-white"
                        >
                            Go To Contract Inbox
                        </button>
                        <button
                            type="button"
                            onClick={handleHistory}
                            className="rounded-md border border-[#D8A37F] bg-white px-5 py-2.5 text-sm font-semibold text-[#B66636]"
                        >
                            Back To Quotation History
                        </button>
                    </div>
                </div>
            </div>
        </div>
    )
}

export default ContractAcceptedDetail
