# Generated by Django 4.2.27 on 2026-07-10 07:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('uniformAdmin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fabric',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fabric_category', to='uniformAdmin.category'),
        ),
        migrations.AddField(
            model_name='fabric',
            name='subcategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fabric_subcategory', to='uniformAdmin.subcategory'),
        ),
    ]
