# Generated by Django 4.2.27 on 2026-07-13 05:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('uniformAdmin', '0003_menu_submenu_rolesubmenupermission_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='parts',
            old_name='category',
            new_name='category_old',
        ),
        migrations.AddField(
            model_name='parts',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parts_category', to='uniformAdmin.category'),
        ),
        migrations.AddField(
            model_name='parts',
            name='subcategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parts_subcategory', to='uniformAdmin.subcategory'),
        ),
    ]
