# Generated by Django 4.2.27 on 2026-07-13 05:23

from django.db import migrations
from django.utils.text import slugify

def migrate_categories(apps, schema_editor):
    Parts = apps.get_model('uniformAdmin', 'Parts')
    Category = apps.get_model('uniformAdmin', 'Category')

    choices_map = {
        "body": "Body",
        "sleeves": "Sleeves",
        "caps": "Caps",
        "straps": "Straps",
        "collars": "Collars",
        "cuffs": "Cuffs",
        "pockets": "Pockets",
        "hoods": "Hoods",
    }

    for part in Parts.objects.all():
        old_val = part.category_old
        if old_val:
            cat_name = choices_map.get(old_val, old_val.capitalize())
            category_obj = Category.objects.filter(categoryName__iexact=cat_name).first()
            if not category_obj:
                category_obj = Category.objects.create(
                    categoryName=cat_name,
                    type='uniform',
                    slug=slugify(cat_name).replace("-", "_"),
                    isActive=True,
                    isDeleted=False,
                )
            part.category = category_obj
            part.save()

def rollback_categories(apps, schema_editor):
    Parts = apps.get_model('uniformAdmin', 'Parts')
    for part in Parts.objects.all():
        if part.category:
            part.category_old = part.category.categoryName.lower()
            part.save()

class Migration(migrations.Migration):

    dependencies = [
        ('uniformAdmin', '0004_parts_category_old_parts_subcategory_and_more'),
    ]

    operations = [
        migrations.RunPython(migrate_categories, reverse_code=rollback_categories),
    ]
