# Generated by Django 4.2.27 on 2026-07-13 05:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uniformAdmin', '0005_migrate_parts_categories'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parts',
            name='category_old',
        ),
    ]
