# Generated by Django 4.2.27 on 2026-07-16 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uniformAdmin', '0006_remove_parts_category_old'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='rental_price_per_day',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='product',
            name='security_deposit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
