# Generated by Django 4.2.27 on 2026-07-27 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uniformAdmin', '0007_product_rental_price_per_day_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(default='KIREIZ SPACE Co., Ltd.', max_length=255)),
                ('business_address', models.TextField(blank=True, null=True)),
                ('support_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('contact_number', models.CharField(blank=True, max_length=50, null=True)),
                ('default_language', models.CharField(default='Japanese', max_length=50)),
                ('default_currency', models.CharField(default='JPY (¥)', max_length=50)),
                ('time_zone', models.CharField(default='(GMT+09:00) Tokyo', max_length=100)),
                ('date_format', models.CharField(default='YYYY/MM/DD', max_length=50)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='system/logos/')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'System Settings',
                'verbose_name_plural': 'System Settings',
            },
        ),
    ]
