# Generated by Django 4.2.27 on 2026-07-27 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uniformAdmin', '0008_systemsettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='rfid_tracking_enabled',
            field=models.BooleanField(default=False),
        ),
    ]
