# Generated by Django 4.2.27 on 2026-08-04 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uniformAdmin', '0009_product_rfid_tracking_enabled'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parts',
            name='partName',
            field=models.CharField(max_length=150),
        ),
    ]
