# Generated by Django 4.2.27 on 2026-08-05 08:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('uniformAdmin', '0010_alter_parts_partname'),
    ]

    operations = [
        migrations.CreateModel(
            name='DashboardAlertRead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(max_length=50)),
                ('fingerprint', models.CharField(max_length=255)),
                ('read_at', models.DateTimeField(auto_now=True)),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dashboard_alert_reads', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name='dashboardalertread',
            constraint=models.UniqueConstraint(fields=('admin', 'alert_type'), name='unique_admin_dashboard_alert_read'),
        ),
    ]
