# Generated by Django 4.2.27 on 2026-08-05 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uniformAdmin', '0011_dashboardalertread_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotationtemplate',
            name='name',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AddField(
            model_name='quotationtemplate',
            name='page_size',
            field=models.CharField(choices=[('A4', 'A4'), ('Letter', 'Letter')], default='A4', max_length=20),
        ),
        migrations.AddField(
            model_name='quotationtemplate',
            name='sort_order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
