# Generated by Django 4.2.27 on 2026-08-05 09:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('uniformAdmin', '0012_quotationtemplate_name_quotationtemplate_page_size_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminuser',
            name='assigned_sales_rep',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_accounts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='adminuser',
            name='designation',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
