# Generated by Django 4.2.27 on 2026-08-05 10:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('uniformAdmin', '0013_adminuser_assigned_sales_rep_adminuser_designation'),
    ]

    operations = [
        migrations.CreateModel(
            name='PdfPageTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('width', models.DecimalField(decimal_places=2, max_digits=10)),
                ('height', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unit', models.CharField(choices=[('mm', 'Millimetres'), ('in', 'Inches'), ('px', 'Pixels')], default='mm', max_length=5)),
                ('tag', models.CharField(blank=True, default='', max_length=30)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='SimulationExportSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('output_format', models.CharField(choices=[('pdf', 'PDF'), ('png', 'PNG'), ('jpg', 'JPG')], default='pdf', max_length=10)),
                ('compression_quality', models.PositiveSmallIntegerField(default=50)),
                ('dpi', models.PositiveSmallIntegerField(choices=[(72, '72 DPI (Screen)'), (150, '150 DPI (Web High Quality)'), (300, '300 DPI (Print)')], default=72)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('selected_template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='export_settings', to='uniformAdmin.pdfpagetemplate')),
            ],
            options={
                'verbose_name': 'Simulation Export Setting',
                'verbose_name_plural': 'Simulation Export Settings',
            },
        ),
    ]
