# Generated by Django 4.2.27 on 2026-08-05 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uniformAdmin', '0014_pdfpagetemplate_simulationexportsetting'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsettings',
            name='admin_notification_emails',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='bank_account_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='bank_account_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='bank_branch',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='bank_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='email_footer_note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='email_reply_to',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='email_sender_address',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='email_sender_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='notify_admin_on_new_request',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='notify_customer_on_registration',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='notify_customer_on_request_received',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='notify_customer_on_status_change',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='payment_terms',
            field=models.TextField(blank=True, help_text="Terms printed on quotations, e.g. '50% advance payment required.'", null=True),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='quotation_validity_days',
            field=models.PositiveSmallIntegerField(default=30, help_text='Default number of days a quotation stays valid.'),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='tax_inclusive',
            field=models.BooleanField(default=False, help_text='Whether quoted figures already include tax.'),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='tax_rate',
            field=models.DecimalField(decimal_places=2, default=10, help_text='Consumption tax percentage shown on quotations.', max_digits=5),
        ),
    ]
