# Generated by Django 4.2.27 on 2026-08-07 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uniformAdmin', '0015_systemsettings_admin_notification_emails_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentCounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_type', models.CharField(help_text='QUO, SO, ...', max_length=10)),
                ('year', models.PositiveSmallIntegerField(help_text='4-digit year')),
                ('last_number', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name='systemsettings',
            name='default_currency',
            field=models.CharField(default='USD ($)', max_length=50),
        ),
        migrations.AddConstraint(
            model_name='documentcounter',
            constraint=models.UniqueConstraint(fields=('doc_type', 'year'), name='unique_document_counter'),
        ),
    ]
