# Generated by Django 4.2.27 on 2026-08-07 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uniformAdmin', '0016_documentcounter_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='parts',
            name='offsetX',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='parts',
            name='offsetY',
            field=models.IntegerField(default=0),
        ),
    ]
