# Generated by Django 4.2.27 on 2026-08-12 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uniformAdmin', '0017_parts_offsetx_parts_offsety'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='bannerImage',
            field=models.ImageField(blank=True, null=True, upload_to='category/banner/'),
        ),
    ]
