# Generated by Django 4.2.27 on 2026-08-12 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uniformAdmin', '0018_product_show_in_simulation'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsettings',
            name='email_host',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='email_password',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='email_port',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='email_use_tls',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='email_username',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
