# Generated by Django 4.2.27 on 2026-08-13 04:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uniformAdmin', '0018_category_bannerimage'),
        ('uniformAdmin', '0020_simulationstructure'),
    ]

    operations = [
    ]
