# Generated by Django 4.2.27 on 2026-08-13 06:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('uniformAdmin', '0021_merge_20260813_0605'),
    ]

    operations = [
        migrations.AddField(
            model_name='template',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='templates', to='uniformAdmin.category'),
        ),
        migrations.AddField(
            model_name='template',
            name='specifications',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
