# Generated by Django 4.2.27 on 2026-08-13 06:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('uniformAdmin', '0022_template_category_template_specifications'),
    ]

    operations = [
        migrations.AddField(
            model_name='template',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='templates', to='uniformAdmin.product'),
        ),
    ]
