# Generated by Django 4.2.27 on 2026-08-13 06:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('uniformAdmin', '0023_template_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='template',
            name='product',
        ),
        migrations.AddField(
            model_name='template',
            name='preset_color',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='templates', to='uniformAdmin.colors'),
        ),
        migrations.AddField(
            model_name='template',
            name='preset_fabric',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='templates', to='uniformAdmin.fabric'),
        ),
    ]
