# Generated by Django 4.2.27 on 2026-08-13 11:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('uniformAdmin', '0024_remove_template_product_template_preset_color_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttributeOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attribute', models.CharField(choices=[('collar', 'Collar'), ('sleeves', 'Sleeves'), ('cap', 'Cap'), ('zipper', 'Zipper'), ('cuff', 'Cuff'), ('pocket', 'Pocket'), ('pants', 'Pant'), ('aprons', 'Apron'), ('size', 'Size')], max_length=30)),
                ('name', models.CharField(max_length=150)),
                ('image', models.ImageField(blank=True, null=True, upload_to='attribute_options/')),
                ('order', models.PositiveIntegerField(default=0)),
                ('isActive', models.BooleanField(default=True)),
                ('isDeleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attribute_options', to='uniformAdmin.category')),
            ],
            options={
                'ordering': ['attribute', 'order', 'id'],
            },
        ),
    ]
