# Generated by Django 4.2.27 on 2026-08-14 03:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uniformAdmin', '0021_merge_20260813_0400'),
        ('uniformAdmin', '0021_merge_20260813_0550'),
        ('uniformAdmin', '0025_attributeoption'),
    ]

    operations = [
    ]
