# Generated by Django 4.2.27 on 2026-08-14 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uniformAdmin', '0026_merge_0021_merge_20260813_0400_0025_attributeoption'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsettings',
            name='alert_awaiting_customer_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='alert_awaiting_customer_sla_days',
            field=models.PositiveSmallIntegerField(default=3),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='alert_pending_review_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='alert_pending_review_sla_days',
            field=models.PositiveSmallIntegerField(default=3),
        ),
    ]
