# Generated by Django 4.2.27 on 2026-08-14 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uniformAdmin', '0027_systemsettings_alert_awaiting_customer_enabled_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsettings',
            name='notify_admin_on_login',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='notify_admin_on_new_registration',
            field=models.BooleanField(default=True),
        ),
    ]
