# Generated by Django 4.2.27 on 2026-09-24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uniformAdmin', '0026_merge_20260814_0358'),
        ('uniformAdmin', '0028_systemsettings_notify_admin_on_login_and_more'),
    ]

    operations = [
    ]
