"""
Django settings for UniformWeb project.

Generated by 'django-admin startproject' using Django 5.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""
import os
from decouple import config
from pathlib import Path
from datetime import timedelta
from dotenv import load_dotenv
import os

BASE_DIR = Path(__file__).resolve().parent.parent
dotenv_path = BASE_DIR / ".env"
load_dotenv(dotenv_path)

# Test immediately
# print("DOCUSIGN_BASE_URL:", os.getenv("DOCUSIGN_BASE_URL"))
# print("DOCUSIGN_ACCOUNT_ID:", os.getenv("DOCUSIGN_ACCOUNT_ID"))
# print("DOCUSIGN_USER_ID:", os.getenv("DOCUSIGN_USER_ID"))
# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-a)&ww89mdf0z@0z_&lm=9ia79zry+d_wi((4x=5-*!ysby@&fz'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True


ALLOWED_HOSTS = [
    "192.168.29.193",
    "192.168.1.31",
    "127.0.0.1",
    "localhost",
    "localhost:7000",
    "localhost:7001",
    "localhost:7002",
    "localhost:7003",
    "192.168.1.56",
    "54.81.43.26",
    "0.0.0.0:8000",
    "0.0.0.0",
    "moira-diamond-unfiltrated.ngrok-free.dev",
]
# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'drf_spectacular',
    'drf_spectacular_sidecar',
    'rest_framework_simplejwt.token_blacklist',
    'rest_framework_simplejwt',
    'corsheaders',
    'uniformAdmin',
    'userhub']
AUTH_USER_MODEL = 'uniformAdmin.AdminUser'


MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    "corsheaders.middleware.CorsMiddleware",
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'UniformWeb.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'UniformWeb.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': BASE_DIR / 'db.sqlite3',
#     }
# }


# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.mysql',
#         'NAME': config('DB_NAME'),
#         'USER': config('DB_USER'),
#         'PASSWORD': config('DB_PASSWORD'),
#         'HOST': config('DB_HOST', default='localhost'),
#         'PORT': config('DB_PORT', default='3306'),
#         'OPTIONS': {
#             'charset': 'utf8mb4',
#             'init_command': "SET NAMES utf8mb4 COLLATE utf8mb4_unicode_ci",
#         },
#     }
# }


DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': config('DB_NAME'),
        'USER': config('DB_USER'),
        'PASSWORD': config('DB_PASSWORD'),
        'HOST': config('DB_HOST', default='localhost'),
        'PORT': config('DB_PORT', default='3306'),
        'OPTIONS': {
            'charset': 'utf8mb4',
            'init_command': "SET NAMES utf8mb4 COLLATE utf8mb4_unicode_ci",
        },
    }
}



# AUTH_USER_MODEL = "uniformAdmin.AdminUser"  # replace yourapp with the actual app name
# AUTH_USER_MODEL = "userhub.Users"



# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"

SITE_DOMAIN = "http://table.104.64.206.82.sslip.io"
# SITE_DOMAIN = "https://t8sjq87n-8002.inc1.devtunnels.ms"

SITE_URL = "http://table.104.64.206.82.sslip.io"

# SITE_URL = "https://t8sjq87n-8002.inc1.devtunnels.ms"

#large file/JSON upload (R.T)
DATA_UPLOAD_MAX_MEMORY_SIZE = 150 * 1024 * 1024
FILE_UPLOAD_MAX_MEMORY_SIZE = 150 * 1024 * 1024


# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": [
        # "rest_framework_simplejwt.authentication.JWTAuthentication",  
        "rest_framework.authentication.SessionAuthentication",
        "userhub.authentication.CustomUserJWTAuthentication",# For Customers
    ],
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.AllowAny',
    ),
    "DEFAULT_SCHEMA_CLASS": "drf_spectacular.openapi.AutoSchema",
    'PAGE_SIZE': 10,
    'DEFAULT_RENDERER_CLASSES': (
        'rest_framework.renderers.JSONRenderer',
    ),
}


CORS_ALLOWED_ORIGINS = [
    "http://localhost:8080",
    "http://127.0.0.1:8000",
    "http://127.0.0.1:8002",
    "http://192.168.1.31:8000",
    "http://192.168.1.56:8000",
    "http://localhost:7000",
    "http://localhost:7001",
    "http://localhost:7002",
    "http://localhost:7003",
    "http://0.0.0.0:8000",
    "http://54.81.43.26",

    # Linode server (nginx par port 80)
    "http://104.64.206.82",
    "http://104.64.206.82:7000",
    "http://104.64.206.82:7001",
    "http://104.64.206.82:7002",
    "http://104.64.206.82:7003",
    "http://table.104.64.206.82.sslip.io",
    "http://admin.104.64.206.82.sslip.io",
    "http://admintable.104.64.206.82.sslip.io",

    # dxtspace.com domains (HTTPS terminated at nginx)
    "https://uniform.dxtspace.com",
    "https://table.dxtspace.com",
    "https://uniform-admin.dxtspace.com",
    "https://table-admin.dxtspace.com",
]

CORS_ALLOW_CREDENTIALS = True
# CORS_ALLOW_ALL_ORIGINS = True

# nginx terminates TLS and forwards X-Forwarded-Proto; without this Django
# treats the request as http and rejects https Origins on POST (CSRF).
SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")

CSRF_TRUSTED_ORIGINS = [
    "https://uniform.dxtspace.com",
    "https://table.dxtspace.com",
    "https://uniform-admin.dxtspace.com",
    "https://table-admin.dxtspace.com",
]


import os

EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"

EMAIL_HOST = os.getenv("MAIL_HOST")
EMAIL_PORT = int(os.getenv("MAIL_PORT", 587))
EMAIL_USE_TLS = os.getenv("MAIL_USE_TLS", "True") == "True"

EMAIL_HOST_USER = os.getenv("MAIL_USERNAME")
EMAIL_HOST_PASSWORD = os.getenv("MAIL_PASSWORD")

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(days=30),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=32),
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True,
}



"stripe payment"
STRIPE_SECRET_KEY = config("STRIPE_SECRET_KEY")
STRIPE_PUBLISHABLE_KEY = config("STRIPE_PUBLISHABLE_KEY")
STRIPE_WEBHOOK_SECRET =config("STRIPE_WEBHOOK_SECRET")
# import os



# Komoju (Unified Payments)
KOMOJU_SECRET_KEY = config("KOMOJU_SECRET_KEY", default="")
KOMOJU_PUBLISHABLE_KEY = config("KOMOJU_PUBLISHABLE_KEY", default="")
KOMOJU_WEBHOOK_SECRET = config("KOMOJU_WEBHOOK_SECRET", default="")

# PayPay Direct
PAYPAY_API_KEY = config("PAYPAY_API_KEY", default="")
PAYPAY_API_SECRET = config("PAYPAY_API_SECRET", default="")
PAYPAY_MERCHANT_ID = config("PAYPAY_MERCHANT_ID", default="")
PAYPAY_WEBHOOK_SECRET = config("PAYPAY_WEBHOOK_SECRET", default="")

# NP Kakebarai Direct
NP_KAKEBARAI_MERCHANT_CODE = config("NP_KAKEBARAI_MERCHANT_CODE", default="")
NP_KAKEBARAI_SP_CODE = config("NP_KAKEBARAI_SP_CODE", default="")
NP_KAKEBARAI_API_KEY = config("NP_KAKEBARAI_API_KEY", default="")

# ONESIGNAL_APP_ID = os.getenv("ONESIGNAL_APP_ID")
# ONESIGNAL_API_KEY = os.getenv("ONESIGNAL_API_KEY")



BASE_DIR = Path(__file__).resolve().parent.parent

STATIC_URL = '/static/'

STATICFILES_DIRS = [
    BASE_DIR / "static",   # your source static files
]

STATIC_ROOT = BASE_DIR / "staticfiles"   # collected files for production


SPECTACULAR_SETTINGS = {
    "TITLE": "Uniform Coordination Apis",
    "DESCRIPTION": "API documentation for UniformCoordination platform",
    "VERSION": "1.0.0",
    "SERVE_INCLUDE_SCHEMA": False,

    # JWT support
    "SECURITY": [{"bearerAuth": []}],
    "COMPONENT_SPLIT_REQUEST": True,

    "SWAGGER_UI_SETTINGS": {
        "persistAuthorization": True,
    },
}


#Docusign 
DOCUSIGN_INTEGRATION_KEY = "2abc67a8-b4d2-439d-8742-e26437450cc1"
DOCUSIGN_USER_ID = "02601a1d-eb9b-41de-a590-ea0c4e99d6ea"
DOCUSIGN_ACCOUNT_ID = "e1187f26-fc71-49cc-b41f-8f1ac6215e5e"
DOCUSIGN_PRIVATE_KEY_PATH = "private.key"

#ngrok for webhook
ALLOWED_HOSTS = ["*"]

# KIREIZ SPACE Configurations
from decimal import Decimal
FLAT_ROUND_TRIP_SHIPPING_FEE = Decimal("1500.00")  # Flat round-trip shipping fee (in yen or local currency)
CLOUDSIGN_CLIENT_ID = os.getenv("CLOUDSIGN_CLIENT_ID", "mock-client-id")
CLOUDSIGN_CLIENT_SECRET = os.getenv("CLOUDSIGN_CLIENT_SECRET", "mock-client-secret")
CLOUDSIGN_BASE_URL = os.getenv("CLOUDSIGN_BASE_URL", "https://sandbox.cloudsign.jp")
