# Generated by Django 4.2.27 on 2026-07-10 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uniformAdmin', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='type',
            field=models.CharField(choices=[('uniform', 'Uniform'), ('table', 'Table')], default='table', max_length=20),
        ),
        migrations.AlterField(
            model_name='category',
            name='type',
            field=models.CharField(choices=[('uniform', 'Uniform'), ('table', 'Table')], default='table', max_length=20),
        ),
        migrations.AlterField(
            model_name='faq',
            name='type',
            field=models.CharField(choices=[('uniform', 'Uniform'), ('table', 'Table')], default='table', max_length=20),
        ),
        migrations.AlterField(
            model_name='privacypolicy',
            name='type',
            field=models.CharField(choices=[('uniform', 'Uniform'), ('table', 'Table')], default='table', max_length=20),
        ),
        migrations.AlterField(
            model_name='product',
            name='productType',
            field=models.CharField(blank=True, choices=[('uniform', 'Uniform'), ('table', 'Table')], default='table', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='type',
            field=models.CharField(choices=[('tablecloth', 'Tablecloth'), ('napkin', 'Napkin'), ('runner', 'Runner'), ('chair_cover', 'Chair Cover'), ('background', 'Background'), ('top', 'Top'), ('bottom', 'Bottom'), ('set', 'Set')], default='set', max_length=30),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='type',
            field=models.CharField(choices=[('uniform', 'Uniform'), ('table', 'Table')], default='table', max_length=20),
        ),
    ]
