# Generated by Django 4.2.27 on 2026-07-18 04:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userhub', '0002_alter_order_order_type_alter_users_usertype'),
        ('uniformAdmin', '0002_alter_blog_type_alter_category_type_alter_faq_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='color',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='color_products', to='uniformAdmin.colors'),
        ),
        migrations.AddField(
            model_name='product',
            name='fabric',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fabric_products', to='uniformAdmin.fabric'),
        ),
        migrations.AddField(
            model_name='product',
            name='rfid_tracking_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='size',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='style',
            field=models.CharField(blank=True, choices=[('premium', 'Premium'), ('standard', 'Standard'), ('luxury', 'Luxury'), ('classic', 'Classic')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='table_shape',
            field=models.CharField(blank=True, choices=[('round', 'Round'), ('rectangle', 'Rectangle'), ('square', 'Square'), ('oval', 'Oval')], max_length=50, null=True),
        ),
        migrations.CreateModel(
            name='InspectionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('returned_qty', models.PositiveIntegerField(default=0)),
                ('good_qty', models.PositiveIntegerField(default=0)),
                ('damaged_qty', models.PositiveIntegerField(default=0)),
                ('notes', models.TextField(blank=True, null=True)),
                ('result', models.CharField(choices=[('pass', 'Pass'), ('fail', 'Fail'), ('pending', 'Pending')], default='pending', max_length=20)),
                ('inspected_at', models.DateTimeField(auto_now_add=True)),
                ('inspected_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inspections', to='userhub.order')),
                ('rental_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inspections', to='userhub.rentalitem')),
            ],
        ),
        migrations.CreateModel(
            name='DamagePhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='damage_photos/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('inspection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='uniformAdmin.inspectionitem')),
            ],
        ),
        migrations.CreateModel(
            name='DamagedItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('reason', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('repair', 'Repair'), ('moved', 'Moved to Available')], default='pending', max_length=20)),
                ('reported_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='damaged_records', to='uniformAdmin.product')),
                ('source_inspection', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='uniformAdmin.inspectionitem')),
            ],
        ),
        migrations.CreateModel(
            name='CleaningItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(choices=[('cleaning', 'Cleaning'), ('finished', 'Finished'), ('moved', 'Moved to Available')], default='cleaning', max_length=20)),
                ('entered_at', models.DateTimeField(auto_now_add=True)),
                ('expected_done_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cleaning_records', to='uniformAdmin.product')),
                ('source_rental_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='userhub.rentalitem')),
            ],
        ),
    ]
