# Generated by Django 4.2.27 on 2026-07-18 05:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('uniformAdmin', '0003_product_color_product_fabric_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tabletheme',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='uniformAdmin.category'),
        ),
        migrations.CreateModel(
            name='ThemeCoverImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='table_themes/covers/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('theme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cover_images', to='uniformAdmin.tabletheme')),
            ],
        ),
        migrations.CreateModel(
            name='ThemeItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(choices=[('table_setup', 'Table Setup'), ('floral_decor', 'Floral Decor'), ('seating', 'Seating'), ('additional_elements', 'Additional Elements')], max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='theme_associations', to='uniformAdmin.product')),
                ('theme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='theme_items', to='uniformAdmin.tabletheme')),
            ],
            options={
                'unique_together': {('theme', 'product', 'section')},
            },
        ),
    ]
