# Generated by Django 4.2.27 on 2026-07-18 08:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userhub', '0002_alter_order_order_type_alter_users_usertype'),
        ('uniformAdmin', '0004_tabletheme_category_themecoverimage_themeitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompensationInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_replacement_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_penalty_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('grand_total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('sent', 'Sent'), ('paid', 'Paid')], default='draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compensation_invoices', to='userhub.order')),
            ],
        ),
        migrations.AddField(
            model_name='inspectionitem',
            name='missing_qty',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='CompensationInvoiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_type', models.CharField(choices=[('missing', 'Missing'), ('damaged', 'Damaged')], max_length=20)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('replacement_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('penalty_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='uniformAdmin.compensationinvoice')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uniformAdmin.product')),
            ],
        ),
    ]
