# Generated by Django 4.2.27 on 2026-07-20 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uniformAdmin', '0006_pricingpackage_promocode_limit_uses_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='rental_price_per_day',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
