# Generated by Django 4.2.27 on 2026-07-22 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uniformAdmin', '0007_product_rental_price_per_day'),
    ]

    operations = [
        migrations.CreateModel(
            name='RentalPolicySettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rental_pricing_formula_label', models.CharField(default='Daily Rate × Quantity × Rental Days', editable=False, help_text='Core formula for calculating rental costs — not editable', max_length=255)),
                ('late_fee_formula_label', models.CharField(default='Rental Value × Late Fee % × Days Overdue', help_text='Descriptive formula label shown to staff on invoices', max_length=255)),
                ('late_fee_rate', models.DecimalField(decimal_places=2, default=5.0, help_text='Late fee rate, percent per day', max_digits=5)),
                ('grace_period_days', models.PositiveIntegerField(default=3, help_text='Days after event before late fees begin to apply')),
                ('flat_shipping_fee', models.DecimalField(decimal_places=2, default=150.0, help_text='Fixed delivery and pickup charge applied once per event', max_digits=10)),
                ('enable_consumption_tax', models.BooleanField(default=True, help_text='Apply sales tax to all taxable transactions')),
                ('tax_percentage', models.DecimalField(decimal_places=2, default=10.0, help_text='Consumption tax percentage applied to taxable rentals', max_digits=5)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Rental Policy Settings',
                'verbose_name_plural': 'Rental Policy Settings',
            },
        ),
    ]
