# Generated by Django 4.2.27 on 2026-08-05 06:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('uniformAdmin', '0009_systemsettings'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.CharField(blank=True, max_length=150, null=True, unique=True)),
                ('icon', models.CharField(blank=True, max_length=100, null=True)),
                ('route', models.CharField(blank=True, max_length=255, null=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('isActive', models.BooleanField(default=True)),
                ('isDeleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name='product',
            name='type',
            field=models.CharField(choices=[('tablecloth', 'Tablecloth'), ('napkin', 'Napkin'), ('runner', 'Runner'), ('chair_cover', 'Chair Cover'), ('background', 'Background')], default='set', max_length=30),
        ),
        migrations.AlterField(
            model_name='role',
            name='role_name',
            field=models.CharField(choices=[('admin', 'Admin'), ('sales_rep', 'Sales Rep'), ('corporate', 'Corporate'), ('customer', 'Customer'), ('b2b', 'B2B'), ('b2c', 'B2C')], max_length=60),
        ),
        migrations.CreateModel(
            name='SubMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.CharField(blank=True, max_length=150, null=True)),
                ('route', models.CharField(blank=True, max_length=255, null=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('isActive', models.BooleanField(default=True)),
                ('isDeleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submenus', to='uniformAdmin.menu')),
            ],
        ),
        migrations.CreateModel(
            name='RoleSubMenuPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('can_view', models.BooleanField(default=True)),
                ('can_create', models.BooleanField(default=False)),
                ('can_update', models.BooleanField(default=False)),
                ('can_delete', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submenu_permissions', to='uniformAdmin.role')),
                ('submenu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_permissions', to='uniformAdmin.submenu')),
            ],
        ),
        migrations.CreateModel(
            name='RoleMenuPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('can_view', models.BooleanField(default=True)),
                ('can_create', models.BooleanField(default=False)),
                ('can_update', models.BooleanField(default=False)),
                ('can_delete', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_permissions', to='uniformAdmin.menu')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu_permissions', to='uniformAdmin.role')),
            ],
        ),
        migrations.AddConstraint(
            model_name='submenu',
            constraint=models.UniqueConstraint(condition=models.Q(('isDeleted', False)), fields=('menu', 'name'), name='unique_submenu_name_per_menu'),
        ),
        migrations.AddConstraint(
            model_name='rolesubmenupermission',
            constraint=models.UniqueConstraint(fields=('role', 'submenu'), name='unique_role_submenu_permission'),
        ),
        migrations.AddConstraint(
            model_name='rolemenupermission',
            constraint=models.UniqueConstraint(fields=('role', 'menu'), name='unique_role_menu_permission'),
        ),
    ]
