# Generated by Django 4.2.27 on 2026-08-05 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uniformAdmin', '0010_menu_alter_product_type_alter_role_role_name_submenu_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='theme',
        ),
        migrations.AlterField(
            model_name='damageditem',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('repair', 'Repair'), ('discard', 'Discard'), ('moved', 'Moved to Available')], default='pending', max_length=20),
        ),
    ]
