# Generated by Django 4.2.27 on 2026-08-07 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uniformAdmin', '0011_remove_product_theme_alter_damageditem_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='inspectionitem',
            name='is_reviewed',
            field=models.BooleanField(default=False),
        ),
    ]
