# Generated by Django 4.2.27 on 2026-08-10 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uniformAdmin', '0012_inspectionitem_is_reviewed'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='show_in_simulation',
            field=models.BooleanField(default=True),
        ),
    ]
