# Generated by Django 4.2.27 on 2026-08-10 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uniformAdmin', '0015_systemsettings_bank_account_holder_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemsettings',
            name='email_host',
            field=models.CharField(default='smtp.gmail.com', max_length=255),
        ),
        migrations.AlterField(
            model_name='systemsettings',
            name='email_password',
            field=models.CharField(blank=True, default='fkfvgfdhjbxphzmm', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='systemsettings',
            name='email_username',
            field=models.CharField(blank=True, default='saksri.s@eqho.com', max_length=255, null=True),
        ),
    ]
