# Generated by Django 4.2.27 on 2026-08-11 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uniformAdmin', '0016_alter_systemsettings_email_host_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemsettings',
            name='email_from_address',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='systemsettings',
            name='email_from_name',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='systemsettings',
            name='email_host',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='systemsettings',
            name='email_password',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='systemsettings',
            name='email_port',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='systemsettings',
            name='email_use_tls',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AlterField(
            model_name='systemsettings',
            name='email_username',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
