# Generated by Django 4.2.27 on 2026-08-11 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uniformAdmin', '0017_alter_systemsettings_email_from_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemsettings',
            name='default_currency',
            field=models.CharField(default='USD ($)', max_length=50),
        ),
    ]
