# Generated by Django 4.2.27 on 2026-08-12 09:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('uniformAdmin', '0018_alter_systemsettings_default_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='fabric',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fabrics', to='uniformAdmin.category'),
        ),
    ]
