# Generated by Django 4.2.27 on 2026-08-13 10:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userhub', '0009_cartitem_custom_theme_order_custom_theme_and_more'),
        ('uniformAdmin', '0020_closure_pattern_size_style_tableshape'),
    ]

    operations = [
        migrations.CreateModel(
            name='LateFeeInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('expected_return_date', models.DateField(blank=True, null=True)),
                ('actual_return_date', models.DateField(blank=True, null=True)),
                ('days_late', models.IntegerField(default=0)),
                ('rate_per_day', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_late_fee', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('notification_message', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('paid', 'Paid')], default='pending', max_length=20)),
                ('is_notified', models.BooleanField(default=False)),
                ('notified_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='late_fee_invoice', to='userhub.order')),
            ],
        ),
    ]
