# Generated by Django 4.2.27 on 2026-08-13 11:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('uniformAdmin', '0021_latefeeinvoice'),
    ]

    operations = [
        migrations.AddField(
            model_name='compensationinvoice',
            name='damaged_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='compensationinvoice',
            name='invoice_number',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='compensationinvoice',
            name='missing_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='compensationinvoice',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='compensationinvoiceitem',
            name='product_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='compensationinvoiceitem',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='uniformAdmin.product'),
        ),
    ]
