# Generated by Django 4.2.27 on 2026-08-13 11:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('uniformAdmin', '0022_compensationinvoice_damaged_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='closure',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='closures', to='uniformAdmin.category'),
        ),
        migrations.AddField(
            model_name='colors',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='colors', to='uniformAdmin.category'),
        ),
        migrations.AddField(
            model_name='pattern',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patterns', to='uniformAdmin.category'),
        ),
        migrations.AddField(
            model_name='size',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sizes', to='uniformAdmin.category'),
        ),
        migrations.AddField(
            model_name='style',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='styles', to='uniformAdmin.category'),
        ),
        migrations.AddField(
            model_name='tableshape',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='table_shapes', to='uniformAdmin.category'),
        ),
    ]
