# Generated by Django 4.2.27 on 2026-08-14 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uniformAdmin', '0023_closure_category_colors_category_pattern_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fabric',
            name='theme',
        ),
    ]
