# Generated by Django 4.2.27 on 2026-07-10 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userhub', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_type',
            field=models.CharField(choices=[('uniform', 'Uniform'), ('table', 'Table')], default='table', max_length=50),
        ),
        migrations.AlterField(
            model_name='users',
            name='userType',
            field=models.CharField(blank=True, choices=[('uniform', 'Uniform'), ('table', 'Table')], default='table', max_length=20, null=True),
        ),
    ]
