# Generated by Django 4.2.27 on 2026-07-27 04:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('uniformAdmin', '0009_systemsettings'),
        ('userhub', '0002_alter_order_order_type_alter_users_usertype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelinfo',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='model_infos', to='uniformAdmin.product'),
        ),
    ]
