# Generated by Django 4.2.27 on 2026-08-05 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userhub', '0003_alter_modelinfo_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_status',
            field=models.CharField(choices=[('success', 'Success'), ('failed', 'Failed'), ('pending', 'Pending'), ('processing', 'Processing')], max_length=20),
        ),
    ]
