# Generated by Django 4.2.27 on 2026-08-05 12:34

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('userhub', '0004_alter_payment_payment_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('contract_id', models.CharField(max_length=50, null=True, unique=True)),
                ('company_name', models.CharField(blank=True, max_length=255, null=True)),
                ('contact_person', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('delivery_date', models.DateField(blank=True, null=True)),
                ('additional_note', models.TextField(blank=True, null=True)),
                ('workflow_status', models.CharField(choices=[('REQUESTED', 'Requested'), ('SENT', 'Sent to Client'), ('SIGNED', 'Client Signed'), ('COMPLETED', 'Completed'), ('DECLINED', 'Declined')], default='REQUESTED', max_length=20)),
                ('contract_status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('signed', 'Signed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('external_document_id', models.CharField(blank=True, max_length=255, null=True)),
                ('signed_pdf', models.FileField(blank=True, null=True, upload_to='signed_contracts/')),
                ('signed_at', models.DateTimeField(blank=True, null=True)),
                ('is_signed', models.BooleanField(default=False)),
                ('cancelled_by', models.CharField(blank=True, max_length=10, null=True)),
                ('cancel_reason', models.TextField(blank=True, null=True)),
                ('isActive', models.BooleanField(default=True)),
                ('isDeleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contracts', to='userhub.order')),
            ],
        ),
        migrations.CreateModel(
            name='ContractAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='userhub.contract')),
            ],
        ),
    ]
