# Generated by Django 4.2.27 on 2026-08-07 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userhub', '0005_contract_contractauditlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='rental',
            name='is_reviewed',
            field=models.BooleanField(default=False),
        ),
    ]
