# Generated by Django 4.2.27 on 2026-08-10 09:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('uniformAdmin', '0016_alter_systemsettings_email_host_and_more'),
        ('userhub', '0006_rental_is_reviewed'),
    ]

    operations = [
        migrations.CreateModel(
            name='ThemeFavourite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_like', models.BooleanField(default=False)),
                ('isActive', models.BooleanField(default=True)),
                ('isDeleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('theme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='theme_favourites', to='uniformAdmin.tabletheme')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_theme_favourites', to='userhub.users')),
            ],
            options={
                'unique_together': {('theme', 'user')},
            },
        ),
    ]
