# Generated by Django 4.2.27 on 2026-08-11 04:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('uniformAdmin', '0016_alter_systemsettings_email_host_and_more'),
        ('userhub', '0007_themefavourite'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUpdateThemes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('config_json', models.JSONField(blank=True, default=dict, null=True)),
                ('design_specifications', models.JSONField(blank=True, default=dict, null=True)),
                ('json_file_path', models.CharField(blank=True, help_text='Stored JSON file path', max_length=500, null=True)),
                ('isActive', models.BooleanField(default=True)),
                ('isDeleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('theme', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='uniformAdmin.tabletheme')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='userhub.users')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('user', 'theme')},
            },
        ),
    ]
