# Generated by Django 4.2.27 on 2026-08-11 06:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userhub', '0008_customupdatethemes'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='custom_theme',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='userhub.customupdatethemes'),
        ),
        migrations.AddField(
            model_name='order',
            name='custom_theme',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='userhub.customupdatethemes'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='custom_theme',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='userhub.customupdatethemes'),
        ),
        migrations.AddField(
            model_name='payment',
            name='custom_theme',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='userhub.customupdatethemes'),
        ),
    ]
