# Generated by Django 4.2.27 on 2026-08-13 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userhub', '0009_cartitem_custom_theme_order_custom_theme_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='deactivation_reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
