# Generated by Django 4.2.27 on 2026-08-14 11:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('userhub', '0010_users_deactivation_reason'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('notification_type', models.CharField(choices=[('shipping', 'Shipping Notification'), ('return_reminder', 'Return Reminder Notification'), ('return_received', 'Return Received Notification'), ('return_not_received', 'Return Not Received Notification'), ('late_fee', 'Late Fee Notification'), ('lost_item', 'Lost Item Notification'), ('compensation_charge', 'Compensation Charge Notice'), ('order_status', 'Order Status Update'), ('general', 'General Notification')], default='general', max_length=50)),
                ('is_read', models.BooleanField(default=False)),
                ('isActive', models.BooleanField(default=True)),
                ('isDeleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_notifications', to='userhub.order')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='userhub.users')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
