services:
  mysql:
    image: mysql:8.0
    container_name: table-mysql
    restart: unless-stopped

    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: table_db
      MYSQL_USER: tableuser
      MYSQL_PASSWORD: tablepass

    ports:
      - "127.0.0.1:3308:3306"

    volumes:
      - mysql_data:/var/lib/mysql

    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-proot123"]
      interval: 5s
      timeout: 5s
      retries: 20

  backend:
    env_file:
      - .env
    build:
      context: .
      dockerfile: Dockerfile

    container_name: table-backend

    restart: unless-stopped

    depends_on:
      mysql:
        condition: service_healthy

    volumes:
      - .:/app

    environment:
      DB_NAME: table_db
      DB_USER: tableuser
      DB_PASSWORD: tablepass
      DB_HOST: mysql
      DB_PORT: "3306"
    


    command: >
      sh -c "
        python manage.py migrate &&
        python manage.py collectstatic --noinput &&
        python manage.py runserver 0.0.0.0:8006
      "

    ports:
      - "8006:8006"

volumes:
  mysql_data:
