# Generated by Django 4.2.27 on 2026-07-14 11:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('uniformAdmin', '0006_remove_parts_category_old'),
        ('userhub', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelinfo',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='model_infos', to='uniformAdmin.product'),
        ),
    ]
