# Generated by Django 4.2.27 on 2026-07-27 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userhub', '0002_alter_modelinfo_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotationrequest',
            name='quotation_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('approved', 'Approved'), ('cancelled', 'Cancelled'), ('accepted', 'Accepted'), ('received', 'Received')], default='pending', max_length=20),
        ),
    ]
